'use strict';window.StackExchange={};function MSIsPlayback(){try{return parent&&parent.WebPlayer}catch(f){return!1}}if(!MSIsPlayback()&&top!=self)throw top.location.replace(document.location),$(function(){$("head").add("body").remove()}),alert("For security reasons, framing is not allowed; click OK to remove the frames."),Error();
StackExchange.init=function(){var f=function(a){if(!window.jQuery)if("complete"!=document.readyState)setTimeout(function(){f(a)},1E3);else{var d=document.createElement("div");d.id="noscript-padding";var c=document.createElement("div");c.id="noscript-warning";c.innerHTML=a+" requires external JavaScript from another domain, which is blocked or failed to load.";document.body.insertBefore(d,document.body.firstChild);document.body.appendChild(c)}},a=function(){$(document).keyup(function(a){27==a.which&&
($("#lightbox:not(.no-esc-remove), .error-popup-dismissable, .popup, .share-tip, .esc-remove").fadeOutAndRemove(),$(".esc-hide").fadeOut(),window.genuwine&&genuwine.isVisible()&&genuwine.click(),window.profileLink&&profileLink.hide())})},c=function(){var a=$("#hlinks"),d=$("#search input[name=q]"),c=d.width(),f=2.5*c,h,g=function(a){d.queue("expand",a)},n=!1,p=!("placeholder"in document.createElement("input"));p&&!StackExchange.options.isMobile&&(""==d[0].value&&(d[0].value="search"),d.bind({focus:function(){"search"==
this.value&&(this.value="")}}));d.keydown(function(c){if(n||46>c.keyCode&&8!=c.keyCode&&32!=c.keyCode)return!0;n=!0;clearTimeout(h);d.clearQueue("expand");g(function(g){d[0].placeholder="";a.fadeOut(100,g)});g(function(a){d.animate({width:f,"max-width":f},100,a)});g(function(){0==d.parent().find(".search-prompt").length&&d.before('<span class="search-prompt">search:</span>')});3==d.queue("expand").length&&d.dequeue("expand")}).focusout(function(){h=setTimeout(function(){g(function(a){d.parent().find(".search-prompt").remove();
a()});g(function(a){d.animate({width:c,"max-width":c},100,a)});g(function(g){p&&""==d[0].value&&(d[0].value="search");d[0].placeholder="search";a.fadeIn(100,g)});3==d.queue("expand").length&&d.dequeue("expand");n=!1},200)});$("#search").keydown(function(a){if(13==a.which&&a.ctrlKey&&d.val())return window.open("/search?q="+encodeURIComponent(d.val()),"_newtab"),!1}).find("input[name=q]").keyup(function(a){27==a.which&&$(this).blur()})};return function(e){StackExchange.options=e;var d=e.serverTime-
(new Date).getTime()/1E3;f(e.site.name);$.ajaxSetup({cache:!1});StackExchange.init.createJqueryExtensions();$(function(){a();c();StackExchange.using(StackExchange.options.user.isAnonymous?"anonymous":"loggedIn",function(){StackExchange.initialized.resolve()},!0,e.fullPostfix);var f=StackExchange.options.styleCodeAdditionalLang;f&&StackExchange.ifUsing("prettify",function(){return StackExchange.loadJsFile("third-party/prettify/additional-langs/"+f)});StackExchange.ready(function(){genuwine.init(e.user.accountId||
null,e.user.inboxUnviewedCount,e.user.notificationsUnviewedCount);e.user.messages&&StackExchange.notify.showMessages(e.user.messages,e.isMobile);e.site.globalAuthDisabled||(!e.site.isChildMeta&&e.user.isAnonymous&&gauth.checkStackAuth(e.stackAuthUrl),gauth.informStackAuth(e.stackAuthUrl));e.user.isAnonymous||profileLink.init(e.user.gravatar,e.isMobile,e.user.profileUrl+"?tab=activity",d);e.enableUserHovercards&&StackExchange.usermenu.init();StackExchange.tagPreferences?StackExchange.tagPreferences.init():
StackExchange.tagmenu.init();$("*[data-tracker]").track()})})}}();
StackExchange.debug={log:function(){},init:function(){this.log=function(f){$(function(){var a=$("#debug-messages");a.length||(a=$("<div id='debug-messages' style='text-align:left;position:fixed;top:50px;left:50px;z-index:1000;background:white;border:2px solid black;width:300px;padding:10px;' />").append($("<span style='cursor:pointer;color:#999'>(close debug messages)</span>").click(function(){$("#debug-messages").remove()})).appendTo("body"));$("<div style='margin-top:10px' />").text(f).appendTo(a)})}}};
StackExchange.initialized=$.Deferred();StackExchange.ready=function(f){StackExchange.initialized.done(f)};if(window.serq)for(var i=0;i<window.serq.length;i++)StackExchange.ready(window.serq[i]);
(function(){var f={anonymous:"full-anon.js",loggedIn:"full.js",prettify:"prettify-full.js",pseudoModerator:"moderator.js",inlineEditing:"full.js",editor:"wmd.js",autocomplete:"third-party/jquery.autocomplete.min.js",tagAutocomplete:"tageditor.js",tagEditor:"tageditornew.js",tagSuggestions:"tagsuggestions.js",mobile:"mobile.js",help:"help.js",inlineTagEditing:"inline-tag-editing.js",mathjaxEditing:"mathjax-editing.js",revisions:"revisions.js",mockups:"mockups.js",review:"review.js",translation:"full.js",
gps:"full-anon.js",postValidation:"post-validation.js"},a={},c={},e,d={},k=function(a,d){return function(g){var c=a[g];c||(c=a[g]=d(g));return c}},j=function(g){var g=a[g],d,c=$.Deferred(),e=$.when(c),f;if(g)for(d=0;d<g.length;d++)(f=g[d].call(null))&&$.isFunction(f.promise)&&(e=$.when(e,f));c.resolve();return e},h=function(){if(!e){var a=$("script[src*='/stub.js']:first");0==a.length?(StackExchange.debug.log("couldn't figure out location of stub.js"),e="/content/js/"):e=a.attr("src").replace(/\/stub\.js.*$/,
"/")}return e},g=function(a){var g=$.Deferred(),d=document.createElement("script");d.async="async";d.type="text/javascript";d.src=a;d.onload=d.onreadystatechange=function(a,c){if(!d.readyState||/loaded|complete/.test(d.readyState))c?g.reject():g.resolve()};d.onerror=function(){g.reject()};$("head")[0].appendChild(d);return g.promise()},n=function(a){a=f[a];return!a?$.Deferred().reject().promise():p(a)},p=k({},function(a){var c=h()+a;var e=d["js/"+a];e?a="?v="+e:(StackExchange.debug.log("no cache breaker for "+
a),a="");return g(c+a)}),u=k({},function(a){function d(){(c=StackExchange[a])?j(a).done(function(){g.resolve()}):0<e?(e--,StackExchange.debug.log("retrying "+a),setTimeout(d,20)):(StackExchange.debug.log("object "+a+" not available although file was loaded"),g.reject())}var g=$.Deferred(),c=StackExchange[a],e=3;c?g.resolve():n(a).done(d).fail(g.reject);return g.promise()}),s=$.Deferred(),t=function(a,g,d,c){if(!d&&!s.isResolved())s.done(function(){t(a,g)});else{if(d)for(var e in f)f.hasOwnProperty(e)&&
(f[e]=f[e].replace(/^(full(?:-anon)?).js$/,"$1"+(c||"")+".js"));c=u(a);d?s.resolve():c=$.when(c,StackExchange.initialized);c.done(function(){g()}).fail(function(){StackExchange.debug.log("failed to provide object "+a)});return c}};t.setCacheBreakers=function(a){for(var g in a)a.hasOwnProperty(g)&&(d[g]=a[g])};StackExchange.using=t;StackExchange.ifUsing=function(g,d,e){if("undefined"!==typeof e){if(c["u_"+e])return;c["u_"+e]=!0}StackExchange[g]?d():((e=a[g])||(e=a[g]=[]),e.push(d))};StackExchange.loadJsFile=
function(a){return g(h()+a)}})();String.prototype.format=function(){var f=this.toString();if(!arguments.length)return f;var a="string"==typeof arguments[0]?arguments:arguments[0],c;for(c in a)f=f.replace(RegExp("\\{"+c+"\\}","gi"),a[c]);return f};String.prototype.truncate=function(f,a){var c=this.toString();f&&c.length>f&&(c=c.substr(0,f)+a);return c};String.prototype.splitOnLast=function(f){f=this.lastIndexOf(f);return 0>f?[this]:[this.substr(0,f),this.substr(f)]};
String.prototype.contains=function(f){return-1<this.indexOf(f)};
StackExchange.init.createJqueryExtensions=function(){var f=StackExchange.helpers;$.extend($.expr[":"],{working:function(a){a=$(a).data("working");return"undefined"!==typeof a&&a},data:function(a,c,e){c=e[3];a=$(a).data(c);switch(typeof a){case "undefined":return!1;case "boolean":return a;case "object":return null!==a}return!0}});$.fn.extend({working:function(a){return this.each(function(){$(this).data("working",a)})},track:function(){return this.each(function(){var a=$(this),c=a.is("a[href]")?a:a.find("a[href]"),
e=a.data("tracker");c.each(function(){var a=this.href.splitOnLast("#"),c=a[0];this.href=c+=(c.contains("?")?"&":"?")+e+(a[1]||"")})})},fadeOutAndRemove:function(){return this.each(function(){var a=$(this);a.fadeOut("fast",function(){a.trigger("removing").remove()})})},charCounter:function(a){return this.each(function(){var c=a.target?$(a.target):$(this).parents("form").find("span.text-counter"),e=this;$(this).bind("blur focus keyup paste",f.DelayedReaction(function(){var d=a.min,f=a.max,j=a.setIsValid||
function(){},h=e.value?e.value.replace(/\r\n/g,"\n").length:0,g=h>0.8*f?"supernova":h>0.6*f?"hot":h>0.4*f?"warm":"cool",n="";0==h?(n="enter at least "+d+" characters",j(!1)):h<d?(n=d-h+" more to go...",j(!1)):(d=f-h,n=0<=d?d+" character"+(1!=d?"s":"")+" left":"too long by "+Math.abs(d)+" character"+(-1!=d?"s":""),j(h<=f));c.text(n);c.hasClass(g)||c.removeClass("supernova hot warm cool").addClass(g)},100,{sliding:!0}).trigger)})},selectRange:function(a,c){return this.each(function(){if(this.setSelectionRange)this.focus(),
this.setSelectionRange(a,c);else if(this.createTextRange){var e=this.createTextRange();e.collapse(!0);e.moveEnd("character",c);e.moveStart("character",a);e.select()}})},addSpinner:function(a){return this.each(function(){f.addSpinner(this,a)})},addSpinnerAfter:function(a){return this.each(function(){$(this).after(f.getSpinnerImg(a))})},removeSpinner:function(){return this.each(function(){$(this).find("img.ajax-loader").remove()})},showErrorPopup:function(a,c){return this.each(function(){f.showErrorPopup(this,
a,c)})},center:function(){var a=this.parent();"static"===a.css("position")&&(a=a.offsetParent());var a=a.offset(),c=$(window);this.css("position","absolute");this.css("top",Math.max((c.height()-this.outerHeight())/2+c.scrollTop()-a.top,0)+"px");this.css("left",Math.max(20,(c.width()-this.outerWidth())/2+c.scrollLeft()-a.left)+"px");a="calc(50% - "+this.outerWidth()/2+"px)";this.css("left",a);this.css("left","-webkit-"+a);return this},helpOverlay:function(){f.bindHelpOverlayEvents(this);return this},
hideHelpOverlay:function(){f.hideHelpOverlay(this);return this},enable:function(){0==arguments.length||arguments[0]?this.removeAttr("disabled").css("cursor","pointer").removeClass("disabled-button"):this.attr("disabled","disabled").css("cursor","default").addClass("disabled-button");return this},disable:function(){return this.enable(!1)},loadPopup:function(a){var c=this;c.addSpinnerAfter({padding:"0 3px"});$.ajax({type:"GET",url:a.url,dataType:"html",success:function(e){var d=$(e).elementNodesOnly();
d.find(".popup-actions-cancel, .popup-close a").click(function(){d.fadeOutAndRemove();a.lightbox&&$("#lightbox").fadeOutAndRemove()});d.find("input:radio[disabled=disabled] + label.action-label").addClass("action-disabled");a.hideDescriptions&&d.find("ul.action-list > li:not(.action-selected) .action-desc").hide();e=d.find("input:radio:not(.action-subform input)");e.closest("li").bind("hide-action",function(){var d=$(this),g=".action-subform"+(a.hideDescriptions?", .action-desc":"");d.removeClass("action-selected").find(g).slideUp("fast")}).bind("show-action",
function(){var c=$(this);c.hasClass("action-selected")||(c.siblings(".action-selected").trigger("hide-action"),c.addClass("action-selected").find(".action-subform").slideDown("fast",function(){a.subformShow&&a.subformShow($(this));if(a.subformFocusInput){var g=$(this).find("input[type=text], textarea").not(".actual-edit-overlay").eq(0);g.length&&g.focus()}}),a.hideDescriptions&&c.find(".action-desc").slideDown("fast"),a.actionSelected&&a.actionSelected(c),d.find(".popup-submit").enable())});e.click(function(){$(this).closest("li").trigger("show-action")});
d.appendTo(c.parent());a.loaded&&a.loaded(d);e=function(){};if(a.subformShow){var f=d.find("li.action-selected .action-subform");0<f.length&&(e=function(){f.each(function(){a.subformShow($(this))})})}if(a.lightbox){var j=$('<div id="lightbox"/>').appendTo($("body")).css("height",$(document).height()).fadeIn("fast");d.css("z-index",j.css("z-index")+1)}a.dontCenter||d.center().fadeIn("fast",e)},error:function(){c.parent().showErrorPopup("Unable to load popup - please try again")},complete:f.removeSpinner});
return c},asyncLoad:function(){return this.each(function(){var a=$(this),c=a.find(".async-load");a.hasClass(".async-load")&&(c=c.add(a));c.each(function(){var a=$(this),d=a.data("load-url")||"";d&&!a.is(":working")&&(a.working(!0).addSpinner(),$.ajax({type:"GET",url:d,dataType:"html"}).done(function(d){a.html(d).removeClass("async-load").mathjax();if(d=a.data("after-load")||""){for(var d=d.split("."),c,f=0;f<d.length;f++)c=(c||window)[d[f]];"function"===typeof c&&c(a)}}).fail(function(){a.removeSpinner().showErrorPopup("An error has occurred; please try again")}))})})},
mathjax:function(){return this.each(function(){"undefined"!=typeof MathJax&&MathJax.Hub.Typeset(this)})},elementNodesOnly:function(){return this.filter(function(){return 1===this.nodeType})}})};
StackExchange.helpers=function(){function f(a,d,c){for(var f=0;f<c.length;f++){var e=c[f];try{if(/\*/.test(e))for(var k=0;4>k;k++){var h=e.replace(/\*/g,j[k]),v=a.css(h);d.css(h,v)}else d.css(e,a.css(e))}catch(l){}}}function a(a,d,c,e){if(a.is(":visible")){var k=$.browser.msie?0:0.4;c()?(a.css("opacity",k+(e?0.2:0)),a.addClass("edit-field-overlayed"),c=a.prev(".actual-edit-overlay"),0==c.length&&(e=a.parent().find("span.edit-field-overlay").text(),c=a.width(),k=a.height(),c=a.clone().prop("className",
"actual-edit-overlay").attr("name",null).attr("id",null).attr("disabled","disabled").css({position:"absolute",backgroundColor:"white",color:"black","-webkit-text-fill-color":"black",opacity:1,width:c,height:k}),c.is("textarea,input")?(c.val(e),f(d,c,["line-height"])):c.text(e).css("line-height",k+"px").prepend("&nbsp;"),f(d,c,["font-family","font-size","text-align"]),f(a,c,["border-*-style","border-*-color","border-*-width"]),a.css({zIndex:1,position:"relative"}),c.insertBefore(a),e=a.offset().top-
c.offset().top,0!=e&&(d=parseInt(c.css("margin-top")),e=d+e,a.is("textarea")||(e=parseInt(c.prevAll(":visible").eq(0).css("margin-bottom"))+d),c.css("margin-top",e)),a=a.offset().left-c.offset().left,0!=a&&(d=parseInt(c.css("margin-left")),c.css("margin-left",d+a)))):a.css("opacity",1).css("filter","").removeClass("edit-field-overlayed")}}function c(a,c){$(a).find("input[type='submit']").prop("disabled",c)}var e,d,k,j=["left","right","top","bottom"],h={bindMovablePopups:function(){var a=function(){e=
d=null;$("body").removeAttr("style")};$("div.popup").each(function(a,c){var f=$(c).find(".handle");f.length&&(f.css({cursor:"move"}),f.unbind("mousedown").bind("mousedown",function(a){var f=$(c).offset();d={x:f.left-a.pageX,y:f.top-a.pageY};e=$(c);f=e.offset();e.offset(f).offset(f);$("body").attr("style","cursor:move");a.preventDefault()}))});k||(k=!0,$(document).on("mousemove",function(a){e&&e.offset({top:a.pageY+d.y,left:a.pageX+d.x})}).on("keypress",a).on("mouseup",a))},genericBindOverlayEvents:function(c,
d,e){StackExchange.options.isMobile||d.bind("keydown contextmenu",function(){h.hideHelpOverlay(c)}).focus(function(){a(c,d,e,!0)}).on("blur change",function(){a(c,d,e)}).each(function(){a(c,d,e)})},bindHelpOverlayEvents:function(a){a.each(function(){var a=$(this);h.genericBindOverlayEvents(a,a,function(){return""===a.val()})})},hideHelpOverlay:function(a){a.css("opacity",1);a.css("filter","");a.removeClass("edit-field-overlayed")},onClickDraftSave:function(a){$(a).click(function(){var a=this.href;
StackExchange.cardiologist.ensureDraftSaved(function(){window.onbeforeunload=null;window.location.href=a});return!1});return!0},showErrorPopup:function(a,c,d){var e,f,k,h,a=$(a);if(a.length){d=$.extend({},{position:"inside",dismissable:!0,type:"alert",closeOtherPopups:!0},d);d.closeOtherPopups&&$(".error-popup").fadeOutAndRemove();var j=$('<div class="error-popup"><div class="error-inner"><div class="error-message"></div></div></div>'),l=j.find(".error-message"),o=j.find(".error-inner");j.addClass("error-popup-"+
d.type);l.html(c);d.dismissable&&(j.addClass("error-popup-dismissable"),l.css("padding-right","35px"),l=$('<div class="error-popup-close" title="close this popup (or hit Esc)">&times;</div>'),o.prepend(l),l.click(function(){j.fadeOutAndRemove()}));d.css&&j.css(d.css);"inside"!=d.position&&"inline"!=d.position&&!d.tip&&(d.tip=d.position.my);d.tip&&o.addClass("error-tip error-tip-"+d.tip.replace(" ","-"));if("inline"==d.position)a.append(j);else if("inside"==d.position)j.css("position","absolute"),
a.append(j);else{j.css("position","absolute");a.offsetParent().append(j);var o=a.position(),l=a.outerWidth(!0),a=a.outerHeight(!0),q=j.outerWidth(),r=j.outerHeight();switch(d.position.at){case "top left":k=0;h=0;break;case "top center":k=0;h=l/2;break;case "top right":k=0;h=l;break;case "right top":k=0;h=l;break;case "right center":k=a/2;h=l;break;case "right bottom":k=a;h=l;break;case "bottom right":k=a;h=l;break;case "bottom center":k=a;h=l/2;break;case "bottom left":k=a;h=0;break;case "left bottom":k=
a;h=0;break;case "left center":k=a/2;h=0;break;case "left top":k=0,h=0}switch(d.position.my){case "left top":e=0;f=-9;break;case "top left":e=-9;f=0;break;case "top right":e=-9;f=q;break;case "right top":e=0;f=q+9;break;case "right bottom":e=r;f=q+9;break;case "bottom right":e=r+9;f=q;break;case "bottom left":e=r+9;f=0;break;case "left bottom":e=r,f=-9}j.css({top:o.top+k-e,left:o.left+h-f})}j.fadeIn();d.transient&&setTimeout(function(){j.fadeOutAndRemove()},Math.max(2500,40*c.length));return j}},
removeErrorPopup:function(){$(".error-popup").fadeOutAndRemove()},addSpinner:function(a,d){$(a).append(h.getSpinnerImg(d))},getSpinnerImg:function(a){var d=$('<img class="ajax-loader" src="/content/img/progress-dots.gif" title="loading..." alt="loading..." />');a&&d.css(a);return d},removeSpinner:function(){$("img.ajax-loader").remove()},enableSubmitButton:function(a){c(a,!1)},disableSubmitButton:function(a){c(a,!0)},loadTicks:function(a){var d;d=a?a.find(".edit-block"):$(".edit-block");0==d.find("input[name=i1l]").length&&
!d.data("loading-ticks")&&(d.data("loading-ticks",!0),$.ajax({url:"/questions/ticks",cache:!1,success:function(a){d.append("<input type='hidden' name='i1l' value='"+a+"' />")},complete:function(){d.data("loading-ticks",!1)}}))},showFancyOverlay:function(a){var a=a||{},d=$("#overlay-header"),c=a.message||"",e=$.browser.msie?{background:"#fff",opacity:0}:{};!1!==a.showClose&&(c+='<br><a class="close-overlay">close this message</a>');d.html(c).css(e).animate({opacity:"1",height:"show"},"slow",a.complete).find(".close-overlay").click(function(){d.animate({opacity:"0",
height:"hide"},"fast")})},DelayedReaction:function(a,d,c){var c=c||{},e,f,k=c.always,h=function(){e=null;a.apply(null,f)};return{trigger:function(){f=arguments;k&&k.apply(null,f);e?c.sliding&&(clearTimeout(e),e=setTimeout(h,d)):e=setTimeout(h,d)},cancel:function(){e&&(clearTimeout(e),e=null)}}},fireAndForget:function(a){$.ajax({type:"POST",url:a,async:!0})}};return h}();
function prepareEditor(f){var a=f.postfix||"",c=function(){setTimeout(function(){StackExchange.editor.initIfShown(f)},1)};if(f.onDemand){for(var e="bold-button,italic-button,spacer1,link-button,quote-button,code-button,image-button,spacer2,olist-button,ulist-button,heading-button,hr-button,spacer3,undo-button,redo-button".split(","),d=$('<ul id="wmd-button-row'+a+'" class="wmd-button-row" />').appendTo(".wmd-button-bar"),k=0,j=0;j<e.length;j++){var h=e[j],g=/spacer/.test(h),h=$("<li id='wmd-"+h+a+
"' />").prop("className","wmd-"+(g?"spacer":"button")).css("left",25*j).appendTo(d);$("<span />").css("background-position",k+"px -20px").appendTo(h);g||(k-=20)}var n=!1;$("#wmd-input, #title, #tagnames, #edit-comment, #m-address, #display-name").one("focus click keydown",function(){n||(n=!0,d.addSpinner({"float":"right"}),StackExchange.using("editor",function(){d.remove();f.autoShowMarkdownHelp&&(f.immediatelyShowMarkdownHelp=!0);c()}))})}else StackExchange.using("editor",c)}
StackExchange.switchMobile=function(f,a){$.post("/mobile/"+f,{returnurl:a},function(a){window.location=a})};
jQuery.cookie=function(f,a,c){if("undefined"!=typeof a){c=c||{};null===a&&(a="",c.expires=-1);var e="";if(c.expires&&("number"==typeof c.expires||c.expires.toUTCString))"number"==typeof c.expires?(e=new Date,e.setTime(e.getTime()+864E5*c.expires)):e=c.expires,e="; expires="+e.toUTCString();var d=c.path?"; path="+c.path:"",k=c.domain?"; domain="+c.domain:"",c=c.secure?"; secure":"";document.cookie=[f,"=",encodeURIComponent(a),e,d,k,c].join("")}else{a=null;if(document.cookie&&""!=document.cookie){c=
document.cookie.split(";");for(e=0;e<c.length;e++)if(d=jQuery.trim(c[e]),d.substring(0,f.length+1)==f+"="){a=decodeURIComponent(d.substring(f.length+1));break}}return a}};jQuery.expr[":"].regex=function(f,a,c){var a=c[3].split(","),e=/^(data|css):/,c=a[0].match(e)?a[0].split(":")[0]:"attr",e=a.shift().replace(e,"");return RegExp(a.join("").replace(/^\s+|\s+$/g,""),"ig").test(jQuery(f)[c](e))};
$.extend($.expr[":"],{containsExact:function(f,a,c){return $.trim(f.innerHTML.toLowerCase())===c[3].toLowerCase()},containsExactCase:function(f,a,c){return $.trim(f.innerHTML)===c[3]},containsRegex:function(f,a,c){a=/^\/((?:\\\/|[^\/])+)\/([mig]{0,3})$/.exec(c[3]);return RegExp(a[1],a[2]).test($.trim(f.innerHTML))}});
$.extend({URLEncode:function(f){for(var a="",c=0,f=f.toString(),e=/(^[a-zA-Z0-9_.]*)/;c<f.length;){var d=e.exec(f.substr(c));null!=d&&1<d.length&&""!=d[1]?(a+=d[1],c+=d[1].length):(" "==f[c]?a+="+":(d=f.charCodeAt(c).toString(16),a+="%"+(2>d.length?"0":"")+d.toUpperCase()),c++)}return a},URLDecode:function(f){for(var a,c=/(%[^%]{2})/;null!=(m=c.exec(f))&&1<m.length&&""!=m[1];)b=parseInt(m[1].substr(1),16),a=String.fromCharCode(b),f=f.replace(m[1],a);return f}});
(function(f){f.fn.typeWatch=function(a){function c(a){if("TEXT"==a.type.toUpperCase()||"TEXTAREA"==a.nodeName.toUpperCase()){var c={timer:null,text:f(a).val().toUpperCase(),cb:e.callback,el:a,wait:e.wait};e.highlight&&f(a).focus(function(){this.select()});var j=function(a){var d=c.wait,j=!1;13==a.keyCode&&"TEXT"==this.type.toUpperCase()&&(d=1,j=!0);clearTimeout(c.timer);c.timer=setTimeout(function(){var a=j,d=f(c.el).val();if(d.length>e.captureLength&&d.toUpperCase()!=c.text||a&&d.length>e.captureLength)c.text=
d.toUpperCase(),c.cb(d)},d)};f(a).keydown(j).bind("paste",null,function(a){a.which||j(this)})}}var e=f.extend({wait:750,callback:function(){},highlight:!0,captureLength:2},a);return this.each(function(){c(this)})}})(jQuery);
(function(f){function a(a){var d;return a&&a.constructor==Array&&3==a.length?a:(d=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(a))?[parseInt(d[1]),parseInt(d[2]),parseInt(d[3])]:(d=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(a))?[2.55*parseFloat(d[1]),2.55*parseFloat(d[2]),2.55*parseFloat(d[3])]:(d=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))?[parseInt(d[1],16),parseInt(d[2],16),parseInt(d[3],16)]:
(d=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(a))?[parseInt(d[1]+d[1],16),parseInt(d[2]+d[2],16),parseInt(d[3]+d[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(a)?c.transparent:c[f.trim(a).toLowerCase()]}f.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(c,d){f.fx.step[d]=function(c){if(!c.colorInit){var e;e=c.elem;var h=d,g;do{g=f.curCSS(e,h);if(""!=g&&"transparent"!=g||f.nodeName(e,"body"))break;h="backgroundColor"}while(e=e.parentNode);
e=a(g);c.start=e;c.end=a(c.end);c.colorInit=!0}c.elem.style[d]="rgb("+[Math.max(Math.min(parseInt(c.pos*(c.end[0]-c.start[0])+c.start[0]),255),0),Math.max(Math.min(parseInt(c.pos*(c.end[1]-c.start[1])+c.start[1]),255),0),Math.max(Math.min(parseInt(c.pos*(c.end[2]-c.start[2])+c.start[2]),255),0)].join()+")"}});var c={transparent:[255,255,255]}})(jQuery);StackExchange.gps=function(){StackExchange._gps_track=[];return{track:function(f,a){a=a||{};StackExchange._gps_track.push({evt:f,properties:a,now:(new Date).getTime()})}}}();
