'use strict';StackExchange.tagEditor=function(d,q,r){function s(){k=!0}function N(){if("undefined"===typeof w){for(var a=StackExchange.tagEditor.requiredTags,b=[],e=0;e<a.length;e++)b.push(a[e].Name.replace(/[.+]/g,"\\$&"));w=RegExp("^(?:"+b.join("|")+")$")}return w}function G(){if(StackExchange.tagEditor.requiredTags&&/^ ?$/.test(c.val())){var a=N();0===g.add(h).children().filter(function(){return a.test($(this).text())}).length&&H(StackExchange.tagEditor.requiredTags)}}function t(a,b){var e=window.tagRendererRaw(a,
null,"span"),e=$(e);b||(e.append('<span class="delete-tag" title="remove this tag"></span>'),f.trigger("tagSpanCreated",[e]));return e}function I(){var a=g.find(".post-tag").map(function(a,b){return $(b).text()}).get().join(" ");a.length&&(a+=" ");var b=h.find(".post-tag").map(function(a,b){return $(b).text()}).get().join(" ");b.length&&c.val().length&&(b=" "+b);return{text:a+c.val()+b,lengthBeforeInput:a.length}}function x(){var a=c.caret();if(g.add(h).find(".post-tag").length){var b=I();c.val(b.text);
g.empty();h.empty();c.caret(a.start+b.lengthBeforeInput,a.end+b.lengthBeforeInput);o()}}function l(a){if(!p){var b;b=a?{start:c.val().length,end:c.val().length}:c.caret();-1==b.start&&(b.start=b.end=0);if(b.start!==b.end)x();else{a=c.val().substr(0,b.start);b=c.val().substr(b.start);a=(a+"!").split(/[,;\s]+/);a[a.length-1]="!"===a[a.length-1]?"":a[a.length-1].slice(0,-1);var e=b.split(/[,;\s]+/),i=a.pop();b=i.length;var i=i+e.shift(),a=sanitizeAndSplitTags(a.join(" ")),e=sanitizeAndSplitTags(e.join(" ")),
j;for(j=0;j<a.length;j++)t(a[j]).appendTo(g);for(j=0;j<e.length;j++)t(e[j]).appendTo(h);i!==c.val()&&c.val(i);f.find(".post-tag").filter(function(){return/^\s*$/.test($(this).text())}).remove();a=I().text;a!=d.val()&&d.val(a).trigger("change");k&&(c.caret(b,b),O(),G())}P()}}function m(a,b){var e,i;if("string"===typeof a)i=a;else if(a.length)e=a,i=e.text();else return;for(var j=sanitizeAndSplitTags(c.val()),d=0;d<j.length;d++)t(j[d]).appendTo(g);c.val(i);e?(i=$($.unique(e.prevAll(".post-tag").get())),
e.nextAll(".post-tag").prependTo(h),i.appendTo(g),e.remove()):h.find(".post-tag").appendTo(g);c.focus();b&&c.caret(0,0)}function J(a){a!==u&&(g.add(c).add(h).css({position:"relative",left:a}),u=a)}function P(){var a;var b=c;a="c_"+b.val();if(a in y)a=y[a];else{var e=$("<span />").css("font-family",b.css("font-family"));e.text(b.val());e.insertAfter(b);b=e.innerWidth();e.remove();a=y[a]=b}a+=19;e=g.outerWidth();h.children().length||(a=Math.max(a,n-e-8));c.css("width",a);0<e+u&&e+u+a<n||(e+a<n?J(0):
J(-e+(n-a)/2))}function K(){z=!0;setTimeout(function(){z=!1},0)}function Q(a){var b=a.find("p.more-info");"undefined"===typeof A&&(A=L-5-b.outerWidth());a.find(".post-tag:first").outerWidth()+a.find(".item-multiplier").outerWidth()>A&&b.find("a").text("info")}function H(a,b){$(".tag-suggestions").remove();p=!1;var e=a.length;if(0!==e){for(var c=$("<div class='tag-suggestions' />").css({position:"absolute",left:f.position().left,top:f.position().top+B+1,width:n-10}).insertAfter(f),d=0;d<a.length;d++){var g=
R(a[d],b).appendTo(c).attr("tabindex",C||0);Q(g);0===d%3&&g.css("clear","both")}c.delegate("div","keydown",S);c.delegate("div","click",function(a){$(a.target).is("a")||D($(this))});c.delegate("div","focus",function(){z&&1===e?D($(this)):p=!0});c.delegate("div","blur",function(){p=!1})}}function O(){var a=sanitizeAndSplitTags(c.val())[0];E!==a&&(E=a,!a||!a.length?o():T(a,function(b){a===E&&k&&H(b,a)}))}function R(a,b){var c=$("<div />").css("width",L).data("tag-name",a.SynonymOf||a.Name);b&&(b=b.replace(/-/g,
"").replace(/(.)(?=.)/g,"$1-*").replace(/\+/g,"\\+").replace(/\./g,"\\."));var d=t(a.Name,!0),f=d.html();b&&(f=f.replace(RegExp("("+b+")"),"<span class='match'>$1</span>"));c.append(d.html(f));a.Count&&c.append($("<span class='item-multiplier' />").html("&times;&nbsp;"+a.Count));d="";a.Excerpt&&(d=a.Excerpt);d.length&&c.append($("<p />").text(d));if(a.Synonyms&&a.Synonyms.length)for(var f=$("<p >also: </p>").appendTo(c),g=a.Synonyms.split(/\|/),h=0;h<g.length;h++)d=g[h],b&&(d=d.replace(RegExp("("+
b+")"),"<span class='match'>$1</span>")),0<h&&(d=", "+d),f.append("<span>"+d+"</span>");c.append("<p class='more-info'><a href='/tags/"+encodeURIComponent(a.SynonymOf||a.Name)+"/info' target='_blank'>learn more</a></p>");return c}function T(a,b){F["t_"+a]?b(F["t_"+a]):M.trigger(a,b)}function D(a){c.val(a.data("tag-name"));o();m("");l()}function o(){$(".tag-suggestions").remove();p=!1;M.cancel()}function S(a){switch(a.which){case 39:case 40:return $(this).next("div").focus(),!1;case 37:return $(this).prev("div").focus(),
!1;case 38:return a=$(this).prev("div"),a.length?a.focus():c.focus(),!1;case 27:return o(),c.focus(),!1;case 13:case 32:return D($(this)),!1}}var k;if("undefined"===typeof r)try{k=d.is(":focus")}catch(V){k=!1}else k=r;d.bind("focus",s);if(d.is(":visible")){d.unbind("focus",s);var n=d.innerWidth(),L=(n-40)/3|0,f=$("<div class='tag-editor' />").css("width",n).insertAfter(d);d.hide();var r=$("<span class='post-tag'>test</span>").appendTo(f),B=f.innerHeight();r.remove();f.css("height",B);var g=$("<span />").appendTo(f),
c=$("<input type='text' tabIndex='0'/>").appendTo(f).val(d.val()+" "),h=$("<span />").appendTo(f),C=d.attr("tabIndex");C&&c.attr("tabIndex",C);var p=!1,w;c.focus(function(){k=!0;G()});var v=!1;f.mousedown(function(){v=!0;$(document).one("mouseup",function(){setTimeout(function(){k||d.trigger("blur");v=!1},0)})});c.blur(function(){k=!1;setTimeout(function(){p||(o(),l(),v||d.trigger("blur"));v=!1},0)});d.focus(function(){c.focus()});c.keydown(function(a){if(a.shiftKey&&U[a.which]||a.ctrlKey&&65===a.which)return x(),
!0;var b=c.caret().start,d=b===c.val().length,f=0===b;switch(a.which){case 37:if(!f)break;m(g.find(".post-tag:last"));return!1;case 39:if(!d)break;m(h.find(".post-tag:first"),!0);return!1;case 8:if(!f)break;a=g.find(".post-tag:last");if(!a.length)return;c.val(a.text()+c.val());c.caret(a.text().length+b);a.remove();return!1;case 46:if(!d)break;a=h.find(".post-tag:first");if(!a.length)return;c.val(c.val()+a.text());c.caret(b,b);a.remove();return!1;case 36:a=g.find(".post-tag:first");if(!a.length)break;
m(a,!0);return!1;case 35:a=h.find(".post-tag:last");if(!a.length)break;m(a);return!1;case 40:return K(),$(".tag-suggestions > div:first").focus(),!1;case 9:K();break;case 27:o();break;case 13:if($(".tag-suggestions").length)return!1}return!0});c.bind("keydown paste click change",function(){setTimeout(function(){l()},0)});f.delegate(".post-tag","click",function(a){var b=$(this);$(a.target).hasClass("delete-tag")&&b.text("");m(b);l()});f.click(function(a){a.target===this&&(m(""),l())});f.on("rerender",
function(){x();l(!0)});var y={},u=0,U={35:!0,36:!0,37:!0,38:!0,39:!0,40:!0},z,E,A,F={},M=StackExchange.helpers.DelayedReaction(function(a,b){StackExchange.helpers.addSpinner(f,{position:"absolute",right:10,top:B/2-2});$.get("/filter/tags",{q:a,newstyle:!0},"json").done(function(c){F["t_"+a]=c;StackExchange.helpers.removeSpinner();b(c)})},400,{sliding:!0});l(!0);StackExchange.helpers.genericBindOverlayEvents(f,c,function(){var a=c.val();return(""===a||" "===a)&&0===g.add(h).children().filter(function(){return!/^\s*$/.test($(this).text())}).length});
StackExchange.tagEditor.ready.resolve();d[0].func_clear=function(){d.val("");c.val("").blur();f.find(".post-tag").remove()};d[0].func_add=function(a){var b=c.val();c.val(a);m(b);l()}}else q=q||0,3>q?setTimeout(function(){d.unbind("focus",s);StackExchange.tagEditor(d,q+1,k)},300):(d.unbind("focus",s),$("body.review-task-page").length||StackExchange.debug.log("tag box is invisible, couldn't start tag editor"))};StackExchange.tagEditor.ready=$.Deferred();
